language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - make pylint
  - make test
after_success:
  coveralls
notifications:
  slack:
    rooms:
      - sys:yeTvjm0bw1tX6MBWrfkVL5RG#travis
